on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch Playlist
        run: |
          curl -f -L "https://stream.kliv.in/Jiotv+144/playlist.html" -o Daksh1.m3u

          # unique line so file always changes
          echo "" >> Daksh1.m3u
          echo "# Updated: $(date -u)" >> Daksh1.m3u

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add Daksh1.m3u
          git commit -m "Playlist update $(date -u)"
          git push
